global:
  scrape_interval: 15s

scrape_configs:
- job_name: resolver
  scheme: https
  scrape_interval: 1s
  static_configs:
  - targets:
    - host.docker.internal:2112
  basic_auth:
    username: <username>
    password: <password>
  tls_config:
    insecure_skip_verify: false